spring:
  application:
    name: task-manager
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0

server:
  port: 8080

# JWT Configuration
jwt:
  secret: YourSuperSecretKeyForJWTGenerationAndValidationThatIsLongEnough
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:4200

# Logging Configuration
logging:
  level:
    com.taskmanager: INFO
    org.springframework.security: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
